version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - DISPLAY=${DISPLAY}
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix  # Monta o socket Unix X11

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
